
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://rakshith91.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Rakshith Bhyravabhotla"
title: "{ Rakshith Bhyravabhotla }"
description: "Website of Rakshith Bhyravabhotla."
keywords: "Rakshith, Bhyravabhotla, personal, jekyll, theme"
favicon: "/img/darth.png"

################
# Header layout #
################

black-favicon: "/img/darth_white.png"

background-img: "../img/watermark.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 15
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Computer Scientist."
  - text: "Machine Learning Enthusiast."
  - text: "Data Miner."

#me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/rakshith91.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/cerner.png"
    date: "Jun 2017 - Present"
    description: "Software Engineer @ Cerner Corporation, Kansas City"
  - image: "/img/timeline/sice.png"
    date: "Aug 2016 - Dec 2016"
    description: "Associate Instructor @ SICE, Indiana University, Bloomington"
  - image: "/img/timeline/cognitive.png"
    date: "May 2016 - May 2017"
    description: "Python Programmer @ Cognitive Science Department, Indiana University"
  - image: "/img/timeline/iu.jpg"
    date: "Aug 2015 - May 2017"
    description: "MS in Computer Science @ Indiana University, Bloomington"
  - image: "/img/timeline/cogni.jpg"
    date: "Sep 2013 - May 2015"
    description: "Programmer Analyst @ Cognizant Technology Solutions, India"
  - image: "/img/timeline/bitm.jpg"
    date: "Aug 2009 - Aug 2013"
    description: "BE in Computer Science @ Birla Institute of Technology, Mesra"

# First image of the Timeline

timeline-img: "/img/timeline/helloworld.png"

############
# Projects #
############

projects:
    - title: "City Navigation"
      url: "https://github.com/rakshith91/CityNavigation"
      description: "Implemented a prototype of Google Maps that gives shortest route in terms of distance, fastest route, route with fewest turns
                    and scenic route that avoids highways given source and destination. Used DFS, BFS, A* search and Iterative Depth first Search algorithms."
    - title: "Stack Analysis"
      url: "https://github.com/rakshith91/Digital-StoryTelling-For-StackExchange"
      description: "Analyzed Stackoverflow metadata providing insights on posts, users, skills and locations. Hosted the data constituting 34 million posts, 8 million users on PostgreSQL.
                    Provided visualizations using Google Charts and D3.js on a web app. Implemented Apriori Algorithm to find out skill sets that go well together and most commonly associated."
    - title: "Mountain Edge Detection"
      url: "https://github.com/rakshith91/POS-Tagger/tree/master/part2"
      description: "Detected the gradient of mountains using Markov Chain Monte Carlo approach. Gibbs sampling is implemented in Python using numpy."
    - title: "Parts of Speech Tagging"
      url: "https://github.com/rakshith91/POS-Tagger"
      description: "Tagged Parts of Speech of words in a sentence using Naive Bayes and Hidden Markov Model. Both bi-gram and tri-gram HMMs have been used."
    - title: "Spam Classification"
      url: "https://github.com/rakshith91/Spam-Classification"
      description: "Classifies if a mail is spam or not with an accuracy of 98%. Naive Bayes and Decision Trees have been used."
    - title: "Image Orientation Detection"
      url: "https://github.com/rakshith91/Neural-Nets"
      description: "The orientation of an image is predicted using two methods: Neural Networks and K-Nearest Neighbors."
    - title: "Customer Loyalty Classification"
      url: "https://github.com/rakshith91/RANG-Technologies-Data-mining-Competition"
      description: "Predicted if a customer is loyal or not using unknown parameters. Finished in top 5% of the competition held by Rang Technologies. xgBoost algorithm has been used."
    - title: "Music Genre Classification"
      url: "http://homes.soic.indiana.edu/bsairamr/Rakshith%20Bhyravabhotla%20-%20main.pdf"
      description: "Classification model to predict the Genre of a music piece. The audio bits are classified into 6 genres widely : Classical, Rock , Jazz, Blues, Metal and Pop.
                    Used an ensemble Random Forests, SVM(Support Vector Machines) and KNN algorithms and achieved an accuracy of 78.14% ."
    - title: "Song Recognition Tool"
      url: ""
      description: "Developed a tool for song recognition which listens to a song (or part of a song) and recognizes what song is playing."
    - title: "Search Engine for Yelp Data Set"
      url: ""
      description: "Predict Categories of a business in Yelp Data Set using only the review text information using Information Retrieval approach. Implemented Page rank algorithm and used Lucene API for indexing."

##########
#Open Source Contributions
##########
open_source_contributions:
    -title: "terra-notification-dialog"
     url: "https://www.npmjs.com/package/terra-notification-dialog"
     description: "terra-notification-dialog is a notification dialog component built over the terra-abstract-modal. It is a common component to be used for confirmation/acceptance criteria style dialogs."
    -title: "terra-dialog-modal"
     url: "https://www.npmjs.com/package/terra-dialog-modal"
     description: "he Dialog Modal allows for dynamic height modals."
    -title: "terra-clinical"
     url: "https://github.com/cerner/terra-clinical/"
     description: "Uplifted terra-clinical framework testing to consume webdriver tests."
###########
# Contact #
###########

email: "rakshith.bhyravabhotla@gmail.com"

################s
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/rakshith91"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/rakshithbhyravabhotla/"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/5307040/rakshith1124"
  - title: "twitter"
    url: "https://twitter.com/byzantine24"
  - title: "facebook"
    url: "https://www.facebook.com/rakshithsai"
  - title: "instagram"
    url: "https://www.instagram.com/rikudo._sennin/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: ""
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Open Source Contributions: 'open_source_contributions'
  Projects: 'projects'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
