
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/' #change it according to your repository name



# Profile information
yourname: Sairam Rakshith  ## put your name
title: 'Programmer - Data Miner - AI Enthusiast'  ## your title
location: Overland Park, KS


## Social Profiles
facebook: https://www.facebook.com/rakshithsai  ## your facebook account url
twitter: https://twitter.com/byzantine24  ## your twitter account url
linkedin: https://www.linkedin.com/in/rakshithbhyravabhotla/   ## your linkedin account url
github: http://www.github.com/rakshith91  ## you dribbble account url
stackoverflow: https://stackoverflow.com/users/5307040/rakshith1124  ## your stackoverflow account url



# Update all the sections by editing the files inside _includes folder.
