
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://rakshith91.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /personal-jekyll-theme

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Sairam Rakshith Bhyravabhotla"
title: "{ Sairam Rakshith Bhyravabhotla }"
description: "Website of Rakshith Bhyravabhotla."
keywords: "Rakshith, Bhyravabhotla, personal, jekyll, theme"
favicon: "/img/darth.png"

################
# Header layout #
################

black-favicon: "/img/darth_white.png"

background-img: "../img/watermark.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 15
start-delay: 200
delete-delay: 2000
lines: # You can add HTML Tags in the Text
  - text: "Computer Scientist."
  - text: "AI Enthusiast."
  - text: "Data Miner."

#me-img: "/img/jetpacktocat.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

me-img: "https://github.com/rakshith91.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/cerner.png"
    date: "Jun 2017 - Present"
    description: "Software Engineer @ Cerner Corporation, Kansas City"
  - image: "/img/timeline/soic.jpeg"
    date: "Aug 2016 - Dec 2016"
    description: "Associate Instructor @ SoIC, Indiana University, Bloomington"
  - image: "/img/timeline/cognitive.png"
    date: "May 2016 - May 2017"
    description: "Python Programmer @ Cognitive Science Department, Indiana University"
  - image: "/img/timeline/iu.jpg"
    date: "Aug 2015 - May 2017"
    description: "MS in Computer Science @ Indiana University, Bloomington"
  - image: "/img/timeline/cogni.jpg"
    date: "Sep 2013 - May 2015"
    description: "Programmer Analyst @ Cognizant Technology Solutions, India"
  - image: "/img/timeline/bitm.jpg"
    date: "Aug 2009 - Aug 2013"
    description: "BE in Computer Science @ Birla Institute of Technology, Mesra"

# First image of the Timeline

timeline-img: "/img/timeline/helloworld.png"

############
# Projects #
############

projects:
    - title: "City Navigattion"
      url: "https://github.com/rakshith91/CityNavigation"
      description: "Navigation system for USA, Canada and Mexico with four options: shortest distance, least time, scenic and least number of turns."
    - title: "Stack Analysis"
      url: "https://github.com/rakshith91/Digital-StoryTelling-For-StackExchange"
      description: "A web app that gives interesting visualizations on Stack Overflow Data."

###########
# Contact #
###########

email: "rakshith.bhyravabhotla@gmail.com"

################s
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/rakshith91"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/rakshithbhyravabhotla/"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/5307040/rakshith1124"
  - title: "twitter"
    url: "https://twitter.com/byzantine24"
  - title: "facebook"
    url: "https://www.facebook.com/rakshithsai"
  - title: "instagram"
    url: "https://www.instagram.com/rikudo._sennin/"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: ""
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Projects: 'projects'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
